"""
Display the model results previously generated by train.py.

This script does not train any models.
"""

import json
import os

import pandas as pd


RESULTS_FILE = "results/model_comparison.csv"
METADATA_FILE = "results/training_metadata.json"


def main():
    """
    Load and display the saved model leaderboard.
    """

    if not os.path.exists(RESULTS_FILE):
        print("Results file was not found.")
        print("Run this command first:")
        print("python src\\train.py")
        return

    results_df = pd.read_csv(RESULTS_FILE)

    results_df = results_df.sort_values(
        by=["F1 Score", "Recall", "Accuracy"],
        ascending=False,
    ).reset_index(drop=True)

    results_df["Rank"] = range(
        1,
        len(results_df) + 1,
    )

    print("=" * 85)
    print("BB84 MODEL COMPARISON")
    print("=" * 85)

    display_df = results_df[
        [
            "Rank",
            "Model",
            "Accuracy",
            "Precision",
            "Recall",
            "F1 Score",
            "False Positives",
            "False Negatives",
            "Training Time (s)",
            "Prediction Time (s)",
        ]
    ].copy()

    percentage_columns = [
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score",
    ]

    for column in percentage_columns:
        display_df[column] = (
            display_df[column] * 100
        ).round(4)

    print(display_df.to_string(index=False))

    best_model = results_df.iloc[0]

    print("\nBest model:")
    print(
        f"{best_model['Model']} — "
        f"{best_model['F1 Score'] * 100:.4f}% F1 score"
    )

    if os.path.exists(METADATA_FILE):
        with open(
            METADATA_FILE,
            "r",
            encoding="utf-8",
        ) as file:
            metadata = json.load(file)

        print("\nExperiment information:")
        print(
            f"Training rows : "
            f"{metadata['training_rows']:,}"
        )
        print(
            f"Testing rows  : "
            f"{metadata['testing_rows']:,}"
        )
        print(
            f"Total time    : "
            f"{metadata['total_execution_time_seconds']:.2f} seconds"
        )


if __name__ == "__main__":
    main()